apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: ${project.artifactId}-configmap
data:
  application.properties: |-
    camel.component.kafka.configuration.brokers=${kafka.cluster-name}-kafka-bootstrap.strimzi.svc:9093
